name: test-workflow

on:
  workflow_dispatch:
jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger other workflow
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/:Shruthi-143/:test-shru-action/actions/workflows/:workflow_id/dispatches \
            -d '{"ref":"main", "inputs": {"parameter_name": "${{ github.event.inputs.parameter_name }}" }}'
